version: 1.0.{build}
image: Visual Studio 2022
build: off

branches:
  only:
    - master
    - /v\d+\.\d+\.\d+.*/

# Skip builds for pull requests to prevent interfering with continuous releases
skip_branch_with_pr: true

environment:
  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64

install:
  - choco source add -n mistuke -s https://www.myget.org/F/mistuke/api/v2
  - choco install -y cabal --version 3.10.2.0
  - choco install -y ghc --version 9.6.5
  - choco install -y msys2
  - choco install -y innosetup
  - refreshenv

before_build:
  - cabal --version
  - ghc --version
  
  # Install build dependencies
  - C:\msys64\usr\bin\bash -lc "pacman -S --needed --noconfirm git mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-qt5-base mingw-w64-x86_64-qt5-declarative mingw-w64-x86_64-qt5-graphicaleffects mingw-w64-x86_64-qt5-imageformats mingw-w64-x86_64-qt5-multimedia mingw-w64-x86_64-qt5-quickcontrols2 mingw-w64-x86_64-qt5-svg mingw-w64-x86_64-qt5-tools mingw-w64-x86_64-qt5-translations mingw-w64-x86_64-qt5-winextras mingw-w64-x86_64-openssl mingw-w64-x86_64-angleproject mingw-w64-x86_64-lmdb mingw-w64-x86_64-libunwind mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib mingw-w64-x86_64-libwebp mingw-w64-x86_64-libjpeg-turbo mingw-w64-x86_64-giflib mingw-w64-x86_64-libwinpthread autoconf autogen automake libtool make"

build_script:
  # Clone HsQML
  - C:\msys64\usr\bin\bash -lc "cd /c/projects && git clone https://github.com/prolic/HsQML

  - cabal update
  - cabal user-config init --force

  # Build secp256k1 from source
  - C:\msys64\usr\bin\bash -lc "cd /c/projects && git clone https://github.com/bitcoin-core/secp256k1 && cd secp256k1 && git checkout v0.5.1 && ./autogen.sh && ./configure --enable-module-schnorrsig --enable-module-extrakeys --enable-module-ecdh --enable-experimental --enable-module-recovery && make && make install"

  # Refresh environment after installing libsecp256k1 from source
  - refreshenv

  # Fix pkg-config files for libsecp256k1 and lmdb with persistent environment
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/futr && export PKG_CONFIG_PATH=C:/msys64/mingw64/lib/pkgconfig:$PKG_CONFIG_PATH && export PATH=/mingw64/bin:$PATH && bash ./platform/windows/fix-pkgconfig-appveyor.sh"  

  # Cabal Build with proper environment
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/futr && export PKG_CONFIG_PATH=C:/msys64/mingw64/lib/pkgconfig:$PKG_CONFIG_PATH && export PATH=/mingw64/bin:$PATH && cabal build --project-file=cabal.project.windows"

  # Build Windows Installer
  - ps: |
      # Get version from futr.cabal
      $version = (Get-Content "futr.cabal" | Where-Object { $_ -match "^version:\s*(.+)" } | ForEach-Object { $matches[1].Trim() })
      Write-Host "Building installer for version: $version"
      
      # Prepare Inno Setup script from template
      $template = Get-Content "platform\windows\innosetup.iss.template"
      $script = $template -replace "@VERSION@", $version
      $script | Set-Content "platform\windows\innosetup.iss"

      # Prepare copy-dlls script from template
      $template = Get-Content "platform\windows\copy-dlls.sh.template"
      $script = $template -replace "@VERSION@", $version
      $script | Set-Content "platform\windows\copy-dlls.sh"

      # Prepare Windows resource file from template
      $template = Get-Content "platform\windows\futr.rc.template"
      $script = $template -replace "@VERSION@", $version
      $script | Set-Content "platform\windows\futr.rc"
      
      # Create dist directory if it doesn't exist
      if (-not (Test-Path "dist")) { New-Item -ItemType Directory -Path "dist" }
      
      # Deploy Qt dependencies
      C:\msys64\usr\bin\bash -lc "cd /c/projects/futr && export PATH=/mingw64/bin:/c/tools/ghc-9.6.5/bin:/c/ProgramData/chocolatey/bin:/usr/bin:`$PATH && windeployqt.exe dist-newstyle/build/x86_64-windows/ghc-9.6.5/futr-$version/build/futr/futr.exe --qmldir=resources/qml"
      
      # Copy additional DLLs
      C:\msys64\usr\bin\bash -lc "cd /c/projects/futr && bash ./platform/windows/copy-dlls.sh"
      
      # Clean up temporary build artifacts
      C:\msys64\usr\bin\bash -lc "cd /c/projects/futr && rm -rf dist-newstyle/build/x86_64-windows/ghc-9.6.5/futr-$version/build/futr/futr-tmp"
      
      # Create Installer Binary
      & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "platform\windows\innosetup.iss"

artifacts:
  - path: dist\futr-*-setup.exe
    name: futr-windows-installer

deploy:
  # Continuous builds from master branch
  - provider: GitHub
    tag: continuous
    release: 🚧 Development Build (Continuous)
    description: |
      ⚠️ This is an automated development build from the latest commit on the master branch.
      This build is not recommended for production use.
    artifact: futr-windows-installer
    auth_token: $(GITHUB_TOKEN)
    prerelease: true
    force_update: true
    on:
      branch: 
        - master

  # Tagged releases
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: Futr $(APPVEYOR_REPO_TAG_NAME)
    description: |
      🎉 Stable release of Futr $(APPVEYOR_REPO_TAG_NAME)

      This is a stable release build. See the changelog for details about what's new in this version.
    artifact: futr-windows-installer
    auth_token: $(GITHUB_TOKEN)
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true
