name:                futr
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/prolic/futr#readme
license:             MIT
author:              Sascha-Oliver Prolic
maintainer:          saschaprolic@googlemail.com
copyright:           2022 Sascha-Oliver Prolic
#category:
extra-source-files:
- README.md

dependencies:
  - aeson
  - base >=4.9 && <5
  - base16 >=0.3.0.1
  - bytestring >=0.10.8 && <0.11
  - cryptohash-sha256
  - data-default
  - datetime
  - directory
  - lens
  - monomer
  - mtl
  - network
  - connection
  - DRBG >=0.5.5 && <0.6
  - parallel-io
  - secp256k1-schnorr
  - serialise
  - stm
  - text
  - text-show
  - vector
  - websockets
  - wuss

executables:
  futr:
    source-dirs:      src
    main:             Main.hs
    extra-libraries:  secp256k1
    extra-lib-dirs:   /usr/local/lib
    ghc-options:
    - -fwarn-incomplete-patterns
    - -threaded
