name: Windows Tests

on:
  pull_request:
  push:
    branches: ["master"]

jobs:
  windows-tests:
    name: Windows Tests
    runs-on: windows-latest
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v4

      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.7'
          cabal-version: '3.10.3.0'

      - name: Cache Cabal packages
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-ghc-9.6.7-cabal-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-ghc-9.6.7-cabal-

      - name: Cache MSYS2 pacman packages
        uses: actions/cache@v4.2.3
        with:
          path: |
            C:\msys64\var\cache\pacman\pkg
          key: ${{ runner.os }}-pacman-pkg-v1
          restore-keys: |
            ${{ runner.os }}-pacman-pkg-

      - name: Initialize Cabal user config
        run: cabal user-config init --force

      - name: Install MSYS2 packages (Qt5, toolchain)
        run: |
          C:\msys64\usr\bin\bash -lc "pacman -Syu --noconfirm"
          C:\msys64\usr\bin\bash -lc "pacman -S --needed --noconfirm git mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-qt5-base mingw-w64-x86_64-qt5-declarative mingw-w64-x86_64-qt5-graphicaleffects mingw-w64-x86_64-qt5-imageformats mingw-w64-x86_64-qt5-multimedia mingw-w64-x86_64-qt5-quickcontrols2 mingw-w64-x86_64-qt5-svg mingw-w64-x86_64-qt5-tools mingw-w64-x86_64-qt5-translations mingw-w64-x86_64-qt5-winextras mingw-w64-x86_64-openssl mingw-w64-x86_64-angleproject mingw-w64-x86_64-lmdb mingw-w64-x86_64-libunwind mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib mingw-w64-x86_64-libwebp mingw-w64-x86_64-libjpeg-turbo mingw-w64-x86_64-giflib mingw-w64-x86_64-libwinpthread autoconf autogen automake libtool make"

      - name: Setup MSYS2 environment
        run: |
          C:\msys64\usr\bin\bash -lc "echo 'export PATH=/usr/bin:/mingw64/bin:/c/tools/ghc-9.6.7/bin:$PATH' >> ~/.bashrc"
          C:\msys64\usr\bin\bash -lc "echo 'export PKG_CONFIG_PATH=C:/msys64/mingw64/lib/pkgconfig:$PKG_CONFIG_PATH' >> ~/.bashrc"

      - name: Clone HsQML
        run: C:\msys64\usr\bin\bash -lc "git clone https://github.com/prolic/HsQML"

      - name: Build secp256k1
        run: |
          C:\msys64\usr\bin\bash -lc "git clone https://github.com/bitcoin-core/secp256k1 && cd secp256k1 && git checkout v0.5.1 && ./autogen.sh && ./configure --enable-module-schnorrsig --enable-module-extrakeys --enable-module-ecdh --enable-experimental --enable-module-recovery && make && make install && cd .."

      - name: Fix pkg-config files
        run: |
          refreshenv
          C:\msys64\usr\bin\bash -lc "bash ./platform/windows/fix-pkgconfig-appveyor.sh"

      - name: Configure
        run: |
          refreshenv
          C:\msys64\usr\bin\bash -lc "cabal configure --enable-tests --project-file=cabal.project.windows"

      - name: Update Cabal package list
        run: cabal update

      - name: Build
        run: |
          refreshenv
          C:\msys64\usr\bin\bash -lc "cabal build --project-file=cabal.project.windows"

      - name: Test
        run: |
          refreshenv
          C:\msys64\usr\bin\bash -lc "cabal test --project-file=cabal.project.windows"
